enabled: true

app:
  image:
    repository: iferlop/administrator-panel
    tag: 30-62610ec
    pullPolicy: Always
  containerPort: 3000
  container:
    name: administrator-panel
    Port: 3000
    replicas: 1

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: admin.ferremat.es
  path: /
  pathType: Prefix

env:
  NEXT_PUBLIC_API_URL: "http://api.ferremat.es"
